# OpenEdx docker-compose stack used for development/test purpose
#
# Nota bene: this docker-compose file requires that you have set the DOCKER_UID
# and DOCKER_GID variables with relevant values (i.e. matching the current
# system user ids). If you use the project's Makefile or the bin/compose
# wrapper, those variable definitions have already been handled on your behalf.
version: "3.4"

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3316:3306"
    env_file: env.d/development
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  mongodb:
    image: mongo:3.2
    # We use WiredTiger in all environments. In development environments we use small files
    # to conserve disk space, and disable the journal for a minor performance gain.
    # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger

  redis:
    image: redis:4

  memcached:
    image: memcached:1.4

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"

  lms:
    build:
      context: ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}
      target: production
      args:
        EDX_RELEASE_REF: ${EDX_RELEASE_REF:-release-2018-08-29-14.14}
    image: edxapp:${EDX_RELEASE:-master}-${FLAVOR:-bare}
    env_file: env.d/development
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.fun.docker_run
    volumes:
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/static/production:/edx/app/edxapp/staticfiles
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/media:/edx/var/edxapp/media
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/store:/edx/app/edxapp/data
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/config:/config
    depends_on:
      - mailcatcher
      - mysql
      - mongodb
      - memcached
      - redis
    user: ${DOCKER_UID}:${DOCKER_GID}

  lms-dev:
    build:
      context: ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}
      target: development
      args:
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID}
        EDX_RELEASE_REF: ${EDX_RELEASE_REF:-release-2018-08-29-14.14}
    image: edxapp:${EDX_RELEASE:-master}-${FLAVOR:-bare}-dev
    env_file: env.d/development
    ports:
      - "8072:8000"
    volumes:
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/src/edx-platform:/edx/app/edxapp/edx-platform
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/static/development:/edx/app/edxapp/staticfiles
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/media:/edx/var/edxapp/media
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/store:/edx/app/edxapp/data
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/config:/config
    command: >
      python manage.py lms runserver 0.0.0.0:8000 --settings=fun.docker_run_development
    depends_on:
      - mailcatcher
      - mysql
      - mongodb
      - memcached
      - redis

  cms:
    image: edxapp:${EDX_RELEASE:-master}-${FLAVOR:-bare}
    env_file: env.d/development
    environment:
      SERVICE_VARIANT: cms
      DJANGO_SETTINGS_MODULE: cms.envs.fun.docker_run
    volumes:
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/static/production:/edx/app/edxapp/staticfiles
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/media:/edx/var/edxapp/media
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/store:/edx/app/edxapp/data
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/config:/config
    depends_on:
      - lms
    user: ${DOCKER_UID}:${DOCKER_GID}

  cms-dev:
    image: edxapp:${EDX_RELEASE:-master}-${FLAVOR:-bare}-dev
    env_file: env.d/development
    ports:
      - "8082:8000"
    volumes:
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/src/edx-platform:/edx/app/edxapp/edx-platform
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/static/development:/edx/app/edxapp/staticfiles
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/media:/edx/var/edxapp/media
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data/store:/edx/app/edxapp/data
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/config:/config
    command: >
      python manage.py cms runserver 0.0.0.0:8000 --settings=fun.docker_run_development
    depends_on:
      - lms-dev

  nginx:
    image: nginx:1.13
    ports:
      - "8073:8071"
      - "8083:8081"
    volumes:
      - ./docker/files/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./${FLAVORED_EDX_RELEASE_PATH:-releases/master/bare}/data:/data:ro
    depends_on:
      - lms
      - cms

  dockerize:
    image: jwilder/dockerize
