version: "3.2"

services:

  mysql:
    image: mysql:5.6
    ports:
        - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: edxapp
      MYSQL_USER: fun
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  mongodb:
    image: mongo:3.2
    # We use WiredTiger in all environments. In development environments we use small files
    # to conserve disk space, and disable the journal for a minor performance gain.
    # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger

  memcached:
    image: memcached:1.4

  rabbitmq:
    image: rabbitmq:3.6

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"

  lms:
    build: .
    image: edxapp:latest
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.fun.docker_run
    volumes:
      - ./config:/config
    depends_on:
      - mailcatcher
      - mysql
      - mongodb
      - memcached
      - rabbitmq

  lms-dev:
    build:
      context: .
      dockerfile: Dockerfile_dev
    image: edxapp:dev
    ports:
      - "8072:8000"
    volumes:
      - ./data/static:/edx/app/edxapp/staticfiles
      - ./data/media:/edx/var/edxapp/media
      - ./config:/config
    command: >
      python manage.py lms runserver 0.0.0.0:8000 --settings=fun.docker_run_development
    depends_on:
      - lms

  cms:
    image: edxapp:latest
    environment:
      SERVICE_VARIANT: cms
      DJANGO_SETTINGS_MODULE: cms.envs.fun.docker_run
    volumes:
      - ./config:/config
    depends_on:
      - lms

  cms-dev:
    image: edxapp:dev
    ports:
      - "8082:8000"
    volumes:
      - ./data/static:/edx/app/edxapp/staticfiles
      - ./data/media:/edx/var/edxapp/media
      - ./config:/config

    command: >
      python manage.py cms runserver 0.0.0.0:8000 --settings=fun.docker_run_development
    depends_on:
      - mailcatcher
      - mysql
      - mongodb
      - memcached
      - rabbitmq

  nginx:
    image: nginx:1.13
    ports:
      - "8073:8071"
      - "8083:8081"
    volumes:
      - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data:/data:ro
    depends_on:
      - lms
      - cms
