version: "3.2"

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3316:3306"
    env_file: env.d/development
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  mongodb:
    image: mongo:3.2
    # We use WiredTiger in all environments. In development environments we use small files
    # to conserve disk space, and disable the journal for a minor performance gain.
    # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger

  memcached:
    image: memcached:1.4

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"

  lms:
    build: .
    image: edxapp:latest
    env_file: env.d/development
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.fun.docker_run
    volumes:
      - ./data/static/production:/edx/app/edxapp/staticfiles
      - ./data/media:/edx/var/edxapp/media
      - ./data/store:/edx/app/edxapp/data
      - ./config:/config
    depends_on:
      - mailcatcher
      - mysql
      - mongodb
      - memcached
    user: "${UID}"

  lms-dev:
    build:
      context: .
      dockerfile: Dockerfile_dev
    image: edxapp:dev
    env_file: env.d/development
    ports:
      - "8072:8000"
    volumes:
      - ./src/edx-platform:/edx/app/edxapp/edx-platform
      - ./data/static/development:/edx/app/edxapp/staticfiles
      - ./data/media:/edx/var/edxapp/media
      - ./data/store:/edx/app/edxapp/data
      - ./config:/config
    command: >
      python manage.py lms runserver 0.0.0.0:8000 --settings=fun.docker_run_development
    depends_on:
      - mailcatcher
      - mysql
      - mongodb
      - memcached
    user: "${UID}"

  cms:
    image: edxapp:latest
    env_file: env.d/development
    environment:
      SERVICE_VARIANT: cms
      DJANGO_SETTINGS_MODULE: cms.envs.fun.docker_run
    volumes:
      - ./data/static/production:/edx/app/edxapp/staticfiles
      - ./data/media:/edx/var/edxapp/media
      - ./data/store:/edx/app/edxapp/data
      - ./config:/config
    depends_on:
      - lms
    user: "${UID}"

  cms-dev:
    image: edxapp:dev
    env_file: env.d/development
    ports:
      - "8082:8000"
    volumes:
      - ./src/edx-platform:/edx/app/edxapp/edx-platform
      - ./data/static/development:/edx/app/edxapp/staticfiles
      - ./data/media:/edx/var/edxapp/media
      - ./data/store:/edx/app/edxapp/data
      - ./config:/config
    command: >
      python manage.py cms runserver 0.0.0.0:8000 --settings=fun.docker_run_development
    depends_on:
      - lms-dev
    user: "${UID}"

  nginx:
    image: nginx:1.13
    ports:
      - "8073:8071"
      - "8083:8081"
    volumes:
      - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data:/data:ro
    depends_on:
      - lms
      - cms
